version: '3.7'
services:
  campusmultiplataforma-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: campusmultiplataforma-front
    ports:
      - '8081:8081'
      - '19001:19001'
      - '19002:19002'
      - '19006:19006'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0


    